languageCode = "en"
languageName = "English"
weight = 1
title = "devgianlu"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
 name = "Gianluca Altomani"
 image = "img/profile_photo.jpg"
 headline = "Backend developer & CTF player"
 bio = "Backend developer interested in cybersecurity and reverse engineering"
 links = [
   { email = "mailto:altomanigianluca@gmail.com" },
   { github = "https://github.com/devgianlu" },
   { gitlab = "https://gitlab.com/devgianlu" },
   { linkedin = "https://linkedin.com/in/devgianlu" },
   { twitter = "https://twitter.com/devgianlu" },
   { stack-overflow = "https://stackoverflow.com/users/5446197/devgianlu" },
 ]
